---

- hosts: all
  become: true
  tasks:

  - name: Update repository index
    apt:
      update_cache: yes

  - name: install apache2 package
    apt:
      name: apache2
      state: latest
  - name: Add PHP support for Apache 
    apt:
      name: libapache2-mod-php
      state: latest

# to run the playbook
# ansible-playbook --ask-become-pass 03_b_update_apache.yml