---

- hosts: all
  become: true
  tasks:

  - name: Update repository index
    apt:
      update_cache: yes
    when: ansible_distibution == "Ubuntu"
    # If using for multiple distributions
    # when: ansible_distribution in ["Ubuntu","Debian"]
    # Match version
    # when: ansible_distribution_version == "18.04"

  - name: install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distibution == "Ubuntu"

  - name: Add PHP support for Apache 
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distibution == "Ubuntu"

# to run the playbook
# ansible-playbook --ask-become-pass 03_a_install_apache.yml